### ISSUE TITLE
[REQUEST] Could you please update this script to python 3 capable with kodi 19?

### ISSUE THREAD

**Issue by Goldenfreddy0703** [BADMS/script.colorbox#3]
Hi, i know its been 2 years but this script works with Auramod and we need need this script updated to kodi 19 capable. Would there be any chance to update this script? I know its been 2 years but it would help keep auramod intact with its features.

**Comment by JacopoV** [comment]
@Goldenfreddy0703 someone started porting to V3  in here (https://forum.kodi.tv/showthread.php?tid=318626&page=12), but i can't get the zip file. It seems it's shared privately or via PM. And so far i had no luck in obtaining it :( 

If you have more luck that me, could you share it ? Many thanks

**Comment by Goldenfreddy0703** [comment]
Wait but couldn't you fork the project?

**Comment by JacopoV** [comment]
I think they can yeah, but I haven't found anything around yet. I tried myself locally to convert to v3, I can install it on Matrix but it crashes and so on.
I have zero knowledge using python tho
